apiVersion: 1
datasources:
  # Altinity ClickHouse Plugin (HTTP Protocol) - DEFAULT
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    uid: clickhouse-ds
    orgId: 1
    access: proxy
    isDefault: true
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: otel
    jsonData:
      defaultDatabase: default
      port: 8123
      server: clickhouse
      dataSourceUrl: http://clickhouse:8123
      addCorsHeader: false
      usePOST: false
      useYandexCloudAuthorization: false
    secureJsonData:
      basicAuthPassword: otel
    editable: true
  
  # Official Grafana ClickHouse Plugin (Native Protocol)
  - name: ClickHouse (official)
    type: grafana-clickhouse-datasource
    uid: clickhouse-official-ds
    orgId: 1
    access: proxy
    isDefault: false
    jsonData:
      defaultDatabase: default
      port: 9000
      host: clickhouse
      username: otel
      protocol: native
      tlsSkipVerify: false
    secureJsonData:
      password: otel
    editable: true

